### ISSUE TITLE
Build fails with onnxruntime 1.13.1

### ISSUE THREAD

**Issue by mweinelt** [rhasspy/larynx2#1]
Hi, wanted to check out larynx2 through nixpkgs and noticed that it doesn't compile with onnxruntime 1.13.1, but works with 1.12.1. Just a heads up.

```
larnyx> [ 50%] Building CXX object CMakeFiles/larynx.dir/main.cpp.o
larnyx> In file included from /build/source/src/cpp/larynx.hpp:13,
larnyx>                  from /build/source/src/cpp/main.cpp:15:
larnyx> /build/source/src/cpp/model.hpp: In function 'void larynx::loadModel(std::string, larynx::ModelSession&)':
larnyx> /build/source/src/cpp/model.hpp:57:22: error: 'struct Ort::Session' has no member named 'GetInputName'
larnyx>    57 |         session.onnx.GetInputName(i, session.allocator));
larnyx>       |                      ^~~~~~~~~~~~
larnyx> /build/source/src/cpp/model.hpp:62:22: error: 'struct Ort::Session' has no member named 'GetOutputName'
larnyx>    62 |         session.onnx.GetOutputName(i, session.allocator));
larnyx>       |                      ^~~~~~~~~~~~~
larnyx> make[2]: *** [CMakeFiles/larynx.dir/build.make:76: CMakeFiles/larynx.dir/main.cpp.o] Error 1
larnyx> make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/larynx.dir/all] Error 2
larnyx> make: *** [Makefile:91: all] Error 2
```

Am I correct to assume that the models are tied to the onnxruntime version?

**Comment by synesthesiam** [comment]
No, the models themselves aren't tied to a specific version of onnxruntime (though they do use operators that require a minimum version, of course).

Looks like there was an API change: https://onnxruntime.ai/docs/api/c/deprecated.html#_deprecated000009

I'll see if I can upgrade to 1.13 :+1:

**Comment by synesthesiam** [comment]
Upgraded to onnxruntime 1.13.1 in larynx version 0.0.2

**Comment by synesthesiam** [comment]
Also, thank you for packing this up :slightly_smiling_face:

**Comment by mweinelt** [comment]
Thank you! I'm excited about the year of the voice, and I'll be actively following it.

**Comment by synesthesiam** [comment]
Treating this issue as a discussion for the moment. @mweinelt given your experience with nix, would you interested in discussing ways to package various services for Rhasspy v3?

I've successfully used guix to create self-contained, relocatable binaries for a few different services (mainly TTS). But I realized that you're much further along with nix if you can build things with the onnxruntime!

**Comment by mweinelt** [comment]
That's an interesting proposal and yes, I would be interested. I think nixpkgs is in a good position to support this ecosystem, we already have many of its dependencies packaged up. I'm primarily active in the python ecosystem in nixpkgs and maintainer for (Coqui) tts and home-assistant, so the overlap is probably ideal.

**Comment by Mic92** [comment]
2 options here that come to my mind:

1. If you want container images that stand by them-self but are still able to share common packages with other containers, you can use docker abstraction in nixpkgs (https://nix.dev/tutorials/building-and-running-docker-images, there is also https://github.com/nlewo/nix2container). This will more or less put packages in its own filesystem layer.
2. To make a writeable store work, what you are describing to work, you would have one container that has a nix-daemon and its socket is mounted into other containers. Each container could than do something like `nix-store -r some/store/path` that pulls from a binary cache.

I think option 1. better explored and you may want to start with that I have used something like option 2 but in my case the nix-daemon was simply installed into the host.

Or maybe I got you wrong and you just want one container with nix and stores all its files outside?

**Comment by synesthesiam** [comment]
Ideally, it would be a single container with the nix daemon installed that could just add to an externally mounted store. This would allow the container to adjust which services are installed, without needing an additional layer on the host (docker compose).

The steps I'm envisioning are:

1. User runs the Rhasspy container, which only contains a web server and nix daemon
2. User selects which services they'd like (speech to text, text to speech, etc.)
3. nix installs those services to the external store (maybe using a custom Rhasspy channel)

**Comment by Mic92** [comment]
cc @MagicRB would be https://github.com/nix-community/NixNG a good base to build this? i.e. does allow the nix store being mounted outside the the container or does it only work with layering.

**Comment by MagicRB** [comment]
Can you clarify what you mean?

**Comment by Mic92** [comment]
> Can you clarify what you mean?

Do build a container with the nix daemon and a writeable nix store mounted from the host.

**Comment by MagicRB** [comment]
Ok so if you want to fully share the store with the host, running a second nix-daemon is not ideal, what you can do is share the daemon too. Just bind mount the socket, so yes, possible

**Comment by synesthesiam** [comment]
But then you need nix on the host too, right?

**Comment by MagicRB** [comment]
Yeah, there is also the option of running the daemon only in the container bit thwn you need one store per container

**Comment by synesthesiam** [comment]
When I've tried to have nix just in the container and the store mounted externally, it's never worked because nix wants to put part of itself in the store.
I've been hoping for a while now that they would add some ability to layers stores :/

**Comment by Mic92** [comment]
Could you not just have the nix-daemon in one container and than each other container is just using this one by sharing the unix socket?

**Comment by synesthesiam** [comment]
I could in a `docker-compose` situation, yes. My goal was a single Docker container though, if possible.

**Comment by Mic92** [comment]
There is actually an alternative. One can also do a single-user nix installation but use file locking instead: https://nixos.wiki/wiki/NFS#Nix_store_on_NFS

**Comment by Mic92** [comment]
The container would need to bind mount some path from the host for that but than you could even have multiple instances of this running without issues.

**Comment by Mic92** [comment]
For bootstrapping nix one could use a static linked nix binary: https://github.com/nix-community/nix-unstable-installer/releases/tag/nix-2.14.0pre20230130_a31d7d4 as this would not need to be started from `/nix`. Let me know if you are interested in this.
